### ISSUE TITLE
你能不能把它做能插件版? (can you made this tools paper/spigot plugin version?)

### ISSUE THREAD

**Issue by leonpano2006** [flashteens/FTMCRailBuilder13#1]
由於這個資料包對於性能吃得太重 
根據pufferfish官方說 大概吃掉了20%的性能
你能不能做一個插件版給大家用
造成的性能問題會好很多

**Comment by flashteens** [comment]
可以提供一下您提到的「pufferfish官方」的完整分析狀況嗎? 或是有沒有相關的討論連結可以參考?
因為我不清楚您所謂「吃掉了20%的性能」是根據什麼環境來當作基準 😅

感謝~

leonpano2006 ***@***.***> 於 2022年8月24日 週三 17:21 寫道：

**Comment by leonpano2006** [comment]
你好快喔 wow
以下是他們的記錄
![image](https://user-images.githubusercontent.com/58368166/186389438-734f4495-ad64-45c1-bf81-16f9f71e5fe0.png)
before disabled https://spark.lucko.me/QJGzA2gtQQ
after disabled https://spark.lucko.me/8mMqyqxWYB

**Comment by leonpano2006** [comment]
如果你想用私訊的
discord id: leonpano#2006
我希望這件事情快速解決就好了

**Comment by flashteens** [comment]
我的 Discord 帳號是 flashteens#4499, 已經寄送交友邀請給您了，麻煩查看一下，感謝~

leonpano2006 ***@***.***> 於 2022年8月24日 週三 18:20 寫道：

**Comment by leonpano2006** [comment]
個人錯誤

**Comment by leonpano2006** [comment]
如果說要做調整的話
把這個issue重新打開吧
